### ISSUE TITLE
Can't clone gitosis-admin.git after initail gitosis with root's id_rsa.pub

### ISSUE THREAD

**Issue by TankyH** [tv42/gitosis#10]
On a server machine, I init gitosis with the root's public key, and git clone git@host:gitosis-admin.git, and terminal prompted me to input git's password, it just can't clone gitosis-admin.git.

Then I deluser git and init gitosis with a local machine's id_rsa.pub, and clone gitosis-admin.git in the same machine, everything just fine.

So,  can I manage gitosis-admin.git in the same machine after init?
btw, how to read gitosis? 
[git to sys]?

any help is greatly appreciated.

**Comment by tv42** [comment]
What you're describing sounds like trouble with SSH keys, not a gitosis bug. I'm not sure what I can do there.

The name comes from https://en.wikipedia.org/wiki/Mitosis

**Comment by TankyH** [comment]
cool name~

**Comment by tv42** [comment]
Closing as likely confusion about SSH, not a gitosis bug.
