### ISSUE TITLE
fatal: 'repo-name.git' does not appear to be a git repository

### ISSUE THREAD

**Issue by JoabeSilva** [tv42/gitosis#5]
When i create the repository, at the moment to execute the git push is given a fatal error
fatal: 'repo-name.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

i have regenerated the public key lot of times, refollowed all the steps and this error continues

**Comment by tv42** [comment]
I'm sorry there's just not enough information here to even determine that your SSH session is served by gitosis. Here's a simple test for that -- you should see this error from gitosis:

```console
$ ssh git@yourserver echo if you see this, it is not gitosis
ERROR:gitosis.serve.main:Unknown command denied
```

To get better help, please provide exact commands run and their outputs, config file, paths, contents of ~git/.ssh/authorized_keys, and such, and reopen. Sorry, there's just not much I can do here.

**Comment by aceqbaceq** [comment]
Hello, i had exactly the same problem.

I checked by 

$ ssh git@yourserver echo if you see this, it is not gitosis

and found out 

that gitosis was not servicing ssh sessions.

I couldnt get why.

As a solution a deleted git user with its home folder and recreated it from scratch.

And it helped.

Hope it helps for you guys.

regards,

Alex K.
